### ISSUE TITLE
constrained environments

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#1]
The email thread "adopt draft-pritikin-anima-bootstrapping-keyinfra as ANIMA WG document" includes comments that "the solution should not claim constrained environments applicability" as this is seen as infringing on the "constrained device" problem space. 

This might be as simple as an overloading of the term "constrained environment" in which case anima doc should change its language to avoid the appearance of overlap. If this is meant to mean environments that don't perform certain features like provide connectivity to a cloud resource this is entirely different than what, e.g., 'ace' means by the term.

**Comment by mcr** [comment]
RFC 7228 uses the term "challenged networks" to distinguish between
nodes that lack processing power/space/energy, from networks that are
unable to provide full size packets, high data-rates.

Addressing constrained systems is neither in the charter, nor excluded from
the charter.

**Comment by pritikin** [comment]
Excellent, it’ll be an easy substitution to make this clearer in the draft abstract. 

- max

**Comment by mcr** [comment]
I believe that this is addressed.
