### ISSUE TITLE
gen art issue #17: clarification of expiry time for voucher 

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#105]
Section 5.5:

> expires-on:  This is set for nonceless vouchers.  The MASA ensures
> the voucher lifetime is consistent with any revocation or pinned-
> domain-cert consistency checks the pledge might perform.  See
> section Section 2.6.1.  There are three times to consider: (a) a
> configured voucher lifetime in the MASA, (b) the expiry time for
> the registrar's certificate, (c) any certificate revocation
> information (CRL) lifetime.  The expires-on field SHOULD be before
> the earliest of these three values.  Typically (b) will be some
> significant time in the future, but (c) will typically be short
> (on the order of a week or less).  The RECOMMENDED period for (a)
> is on the order of 20 minutes, so it will typically determine the
> lifespan of the resulting voucher.

There are several issues here, the lifetimes of the imprinting with
the owner/registrar vs. the lifetimes of the imprinting process
artifacts. Please clarify. I *think* you are talking about the
process expery times above, not about the expiry of the imprinting.
And certainly I'd hope 20min is not the duration of the imprinting,
but rather it needs to be infinite in most cases.

**Comment by pritikin** [comment]
related in 2.6.1 'lack of a realtime clock': For nonceless vouchers, the
      voucher's created-on time COULD be earlier if the as well if a
      long-lived voucher was obtained some time in the past, and the
      pledge has since gone through a firmware update and factory reset.

**Comment by mcr** [comment]
20 minutes is sufficent time to reach the post-provisional state
          in the pledge, at which point there is an established trust
          relationship between pledge and registrar.  The subsequent
          operations can take as long as required from that point onwards.
          The lifetime of the voucher has no impact on the lifespan of the
          ownership relationship.

**Comment by mcr** [comment]
real time clock.  There are some reasonable assumptions
                that can be made:  the voucher's expires-on time can not
                be prior to the pledge's current reasonable date.
                For nonceless vouchers, the voucher's created-on time COULD
                be earlier than the pledge's notion of the time,
                such as if a long-lived voucher was
                obtained some time in the past, and the pledge has since
                gone through a firmware update and factory reset.
