### ISSUE TITLE
gen art issue #18: pinned-domain-cert as trust anchor

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#106]
Section 5.5.2:

> The pinned-domain-cert MAY be installed as an trust anchor for future
> operations.

Could this be used for future imprinting, or only for other things?
Please clarify.

**Comment by pritikin** [comment]
it can not be used for future "imprinting". 

As discussed in draft-18, 5.6.2 (it moved) this is most appropriate for future enrollment (e.g. RFC7030 as recommended) or trust anchor management (e.g. RFC5934) or raw protocols that do not need a real PKI.

**Comment by pritikin** [comment]
https://github.com/anima-wg/anima-bootstrap/commit/872828d49f9cd81819b859d7129b38db63f711b7
