### ISSUE TITLE
gen art issue #20: clarify proximity assertion assurance

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#108]
Section 5.7.2:

> A "proximity" assertion
> assures the registrar that the pledge was truly communicating with
> the prior domain and thus provides assurance that the prior domain
> really has deployed the pledge.

I don't think I understand the promixity assurances. Obviously, the
pledge and the owner's domain are in some kind of communication,
but not sure how that proves proximity, given that requests from
a pledge could easily be tunneled from somewhere else.

**Comment by pritikin** [comment]
Commenter is correct that proximity is a proxy for physical proximity. It is evidence that the registrar has engaged in the TLS connection with the pledge. Requests could be "tunneled from somewhere else". This is a benefit; in fact it is the point of the proxy discussions. 

The value is to provide information to the MASA that it is reasonable to issue a voucher to this registrar with minimal supply chain integration. No judgement is made about the registrar's network topology. 

Places where this is explained include section 5.4.5, 5.7.2, or 6.4. I think 6.4 is the closest to my discussion here but could see how the other sections might benefit by a tweak?

**Comment by mcr** [comment]
related to #120... proximity assertion of a major mode.
