### ISSUE TITLE
gen art issue #21: TOFU extension unclear

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#109]
Section 6.2:

> 2.  The pledge MAY support "trust on first use" for physical
>     interfaces such as a local console port or physical user
>     interface but MUST NOT support "trust on first use" on network
>     interfaces.  This is because "trust on first use" permanently
>     degrades the security for all use cases.
> 
> 3.  The pledge MAY have an operational mode where it skips voucher
>     validation one time.  For example if a physical button is
>     depressed during the bootstrapping operation.  This can be useful
>     if the manufacturer service is unavailable.  This behavior SHOULD
>     be available via local configuration or physical presence methods
>     (such as use of a serial/craft console) to ensure new entities
>     can always be deployed even when autonomic methods fail.  This
>     allows for unsecured imprint.

I think #2 is actually too conservative; with a "TOFU" button one
would reasonably be able to pair devices to a local, previously
untrusted registrar. And #3 is I suppose something along those lines,
but defined quite imprecisely. One should verify the exchanges and
signatures and go through the whole process, but NOT require signature
from the trusted MASA.

**Comment by mcr** [comment]
Very similar: 3 does entire flow, but can provide no feedback to button holder.
situation 2 is much more involved: the operator would enter some set of commands to initiate EST enrolment.

**Comment by pritikin** [comment]
change number 2 to be: many devices already support TOFU on physical interfaces such as console ports. This document does not change that reality. The core point of #2 is that a device that implements additional features such as a TOFU style default password is not recommended since this undermines the security value of BRSKI. Downgrade this to a RECOMMENDATION (e.g. SHOULD NOT).

**Comment by pritikin** [comment]
https://github.com/anima-wg/anima-bootstrap/commit/48395a3b56c165dd6a4c486ccf3156eedad19194
