### ISSUE TITLE
Offline operations

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#11]
referring to version -06.

Brian Carpenter is concerned about supporting deployment cases where the pledge can not be online with the MASA:

> 1) a military network, especially a "tactical" network deployed in
> the battlefield, which is actually a great use case for autonomics,
> 2) a control network requiring extra high security, for example
> the control system for a nuclear power plant.
> In such cases - if I was in charge - I would consider an Internet
> connection to a MASA service to be dangerous and unacceptable.

The abstract claims offline mode is supported. Alas the word offline does occur anywhere else in the document.

> None of these approaches require the network to have permanent
> Internet connectivity.  Even when the Internet based MASA service is
> used, it is possible to pre-fetch the required information from the
> MASA a priori, for example at time of purchase such that devices can
> enroll later.  This supports use cases where the domain network may
> be entirely isolated during device deployment.

This is the paragraph that seem to have been originally created in response to Brians concern.
Problem 1: It is currently only in section D, targeted to be removed.

Problem 2: It seems to date back to a time in BRSKI when MASA was considered optional "even when...". Alas, no other part of the BRSKI seem to explicitly state that MASA is mandatory. At least there is no text explaining that operations without MASA is outside the scope of the document - and would not make sense for BRSKI because it can not be done securely with the BRSKI security model.

Problem 3: That paragraph is only suggestive, but not descriptive. There should be a concise but precise description of how the offline model is supported. Eg, pick a model like: 

 pledge ----- registrar .... USB/sneakernet .... registrar-proxy ------------ MASA
             BRSKI                                                                             BRSKI-MASA

explain with as little text as possible this could work. 
- Could Netconf file formats be used to create a standard USB/sneakernet channel here ? Else the format of data on sneakernet channel is unspecified except that it must contain the same information as what would be on BRSKI-MASA.
- Specify that only specific voucher options can work here ?! Nonce-less ?
- Say that this could be easy (preprovision vouchers into registrar at any time with simple voucher vs. two step with pledge providing proof-of-posession-voucher to registrar first
- explain how registrar can keep pledge waiting.

Or else if there is strng enough feeling that this shouldn't fit into BRSKI, discuss on list that we shold outsource into a separate draft.

**Comment by pritikin** [comment]
I'm closing this since we have the "offline #2" issue opened and being discussed. In response to this issue I did make sure the latest doc has consistent use of the term "offline" so it is easy to search for relevant text.
