### ISSUE TITLE
gen art issue #23: privacy considerations should talk about serial numbers

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#111]
Section 8:

> 8.  Privacy Considerations

This does not discuss the role of serial numbers and other
identifying information.

**Comment by pritikin** [comment]
I guess section 8 could start off by pointing out that the serial number of the device isn't the privacy sensitive information -- its the association of the serial number with a particular registrar that is a privacy consideration. As such the protocol allows for all the stuff currently in section 8. 

Or is there a privacy consideration about the serial number that I'm missing?

**Comment by mcr** [comment]
This is perhaps dealt with in the text for #88.

**Comment by pritikin** [comment]
The bullets at line 2939 of this commit seem to provide sufficient text: https://github.com/anima-wg/anima-bootstrap/commit/4eb34d856c270b3795816af9e34ad38e465bf991

I don't think additional text will help clarify. Any doubts readers have at this point is around their position on if registrar identity is sufficiently obscured but they've the information to make that judgement.
