### ISSUE TITLE
gen art issue #24: add discussion of each major mode of the protocol

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#112]
Section 9:

> 9.  Security Considerations

I expected to find a section that would go through the protocol and
explain the security properties that it has, along with some
discussion of residual vulnerabilities. What I found was a discussion
of a handful of specific issues, such as the impacts of trusting the
manufacturers, or why the nonce design is the way it is in the
protocol.

I'd find it useful to have, say, a discussion for each major
mode of the protocol and what security properties it provides
and does not provide.

**Comment by pritikin** [comment]
This sounds a lot like the discussion from section 6 ("Reduced security operational modes") wherein each major modes of the protocol is discussed from the perspective of the security considerations of using those modes?

**Comment by mcr** [comment]
related to #119?

**Comment by pritikin** [comment]
the sales-channel integrations changes should be used to address this. so the ops considerations discussion should be written to address this.

**Comment by mcr** [comment]
also related to #120 definitions.
