### ISSUE TITLE
gen art nits/editorials

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#113]
> BRSKI provides a solution for secure zero-touch (automated) bootstrap
> of virgin (untouched) devices that are called pledges in this

Maybe s/virgin (untouched)/new (unconfigured)/

> Services that benefit from this:
>  o  Device management.
>  o  Routing authentication.
>  o  Service discovery.

Are these examples? If so, say so? Otherwise, please specify why these services
and not others are suitable for BRSKI.

> the following actions are required and MUST be performed by the
> pledge:
>
>  o  BRSKI: Request Voucher
>  o  EST: CA Certificates Request
>  o  EST: CSR Attributes
>  o  EST: Client Certificate Request
>  o  BRSKI: Enrollment status Telemetry

Actions? Operations? Steps? (Later you use the term operations.)

Would be good to clarify if the listed items are sending a message, or
performing a procedure called <something>, or something else. Wording
here is quite loose.

> 1.5.  Requirements for Autonomic Network Infrastructure (ANI) devices

FWIW, it would have felt more natural to have thee requirements specified in the
ANI documents, rather than here.

> The pledge goes through a series of steps, which are outlined here at
> a high level.

The Section 2.1 steps in the figure do not match the "actions" from
Section 1.5.

> 4.  Imprint on the registrar.  This requires verification of the
>     manufacturer service provided voucher.  A voucher contains
>     sufficient information for the pledge to complete authentication
>     of a registrar.  (The embedded 'pinned-domain-certificate'
>     enables the pledge to finish authentication of the registrar TLS
>     server certificate).

There is a lot going on here. Might have been better to separate the
steps.

> After imprint a secure transport exists between pledge and registrar.

Do you mean there's an open TLS/TCP connection or that there are
credentials&keys to securely communicate between the two?

>   The pledge goes through a series of steps, which are outlined here at
>   a high level.
>
> ...
>
>   |            +------v-------+
>   |            | (6) Enrolled |
>   ^------------+              |
>    Factory     +--------------+

"Enrolled" is not a step, but rather a state...

> 2.  Securely authentating the pledges identity via TLS connection to

typo

> 2.  Securely authentating the pledges identity via TLS connection to

s/pledges/pledge's/?

> registrar.  This provides protection against cloned/fake pledged.

s/pledged/pledge/?

> 3.  Secure auto-discovery of the pledges MASA by the registrar via
>     the MASA URI in IDevID as explained below.

I can't parse the sentence.

> 4.  (Optionally) communicating the MUD URL (see Appendix C.

Missing closing paren.

> The following newly defined field SHOULD be in the PKIX IDevID
> certificate:

I didn't understand the formulation here. Are you defining one
(seems like it below) or are you referencing a newly elsewhere
defined field? Suggest a reformulation, e.g., "This document
defines a new field for PKIX certificates. These fields SHOULD
appear in the PKIX IDevID certificates when used with BRSKI."

> Specifically, the IDevID:
> 
> 1.  Uniquely identifying the pledge by the Distinguished Name (DN)
> ...
> 2.  Securely authentating the pledges identity via TLS connection to
> ...
>  3.  Secure auto-discovery of the pledges MASA by the registrar via
> ...
> 4.  (Optionally) communicating the MUD URL (see Appendix C.
>
> 5.  (Optional) Signing of voucher-request by the pledges IDevID to
> ...
> 6.  Authorizing pledge (via registrar) to receive certificate from

There's something wrong with the language here. Maybe "Specifically,
the IDevID enables the following: 1. Unique identification of the ..."

Section 2.4 protocol flow is very different from the explanation
in Section 2.1, which does not show the role of the background
systems (MASA) at all.

>  P                     |       /--->       |                    |
>  P                     |       |      [accept device?]          |
>  P                     |       |      [contact Vendor]          |
>  P                     |       |           |--Pledge ID-------->|
>  P                     |       |           |--Domain ID-------->|
>  P                     |       |           |--optional:nonce--->|
>  P                     |       |           |     [extract DomainID]
>  P                     |    optional:      |     [update audit log]
>  P                     |       |can        |                    |
>  P                     |       |occur      |                    |
>  P                     |       |in         |                    |
>  P                     |       |advance    |                    |
>  P                     |       |if         |                    |
>  P                     |       |nonceless  |                    |
>  P                     |       |           |<- voucher ---------|
>  P                     |       \---->      |                    |

I had a difficulty in understanding the notation here. Is the
thing in the middle with the label "optional" a bracket that
shows a part of the flow can be at a different place? Or is it
some entity with some messages flowing from it, because it has
arrows? I think the format, but this is unclear.

> The registrar uses an Implicit Trust Anchor database for

Upon the first reference to the term you should include a
reference to RFC 7030.

> be-determined mechanism (such as an Intent) to become the local

Reference needed to "Intent".

> 4.2.  CoAP connection to Registrar
> 
> The use of CoAP to connect from pledge to registrar is out of scope
> for this document, and may be described in future work.

I would just have said other mechanisms can be defined in future work.

> In the nonced case, validation of the registrar MAY be omitted if the

Nonced?

> assertion:  The assetion leaf in the voucher and audit log indicates

Typo

**Comment by pritikin** [comment]
Action for this appears to be that we've addressed all as per the above (or based on subsequent conversations) and reported back.

**Comment by mcr** [comment]
After typos are closed, let's take the bigger question of where requirements go to the list.

**Comment by mcr** [comment]
"nonced" is in the terminology.
