### ISSUE TITLE
consider if unsigned voucher request should be removed, or more clearly specified

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#115]
When a pledge decides to use an unsigned voucher request, the Registrar will place it into prior-signed-voucher request on the BRSKI-MASA arc.  It will be JSON embedded in.
When a pledge decides to use a signed voucher request, the Registrar will place the base64 encode of the pledge_request in as a string.  
The MASA can tell the difference between the two because the signed thing (whether CBOR, COSE, CMS signed CBOR, or CMS signed JSON) will always be base64 encoded.  
We need to explain this somewhere.

**Comment by pritikin** [comment]
section 5.5 indicates that:

prior-signed-voucher-request:  If a signed pledge voucher-request was
      received then it SHOULD be included in the registrar voucher-
      request.  (NOTE: what is included is the complete pledge voucher-
      request, inclusive of the 'assertion', 'proximity-registrar-cert',
      etc wrapped by the pledge's original signature).  If a signed
      voucher-request was not recieved from the pledge then this leaf is
      omitted from the registrar voucher request.

This indicates that the MASA never needs to "tell the difference" only the registrar. (The pledge to registrar signaling is via request media type as detailed in s5.2). 

I did notice this when reading:

s3.3. these references to voucher in the leaf description should be to voucher request?
            "If it is necessary to change a voucher, or re-sign and
             forward a voucher that was previously provided along a
             protocol path, then the previously signed voucher SHOULD be
             included in this field." etc. subsequent paragraphs.

**Comment by pritikin** [comment]
Max to produce a draft branch that removes unsigned voucher request so we can examine the ramifications of this.

**Comment by EskoDijk** [comment]
v20 of BRSKI removed unsigned voucher requests. What were the reasons for removing? I don't see a mention of this in the anima WG email. 
If removed as a final decision, then this issue can be closed also.

**Comment by mcr** [comment]
Hi, yes, we could close this now.
I did post several times to the list in Feb and March, and it was raised during the WG meeting itself, asking for feedback.

**Comment by EskoDijk** [comment]
Ok, I now see the email list discussion also in December 2018 and based on this the unsigned voucher was removed.
