### ISSUE TITLE
EKU and KeyUsage attributes for certificates should be defined

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#122]
In order to do proper interoperability, the set of EKUs and keyUsage extensions that might be mandated by some libraries need to be articulated.  

(MCR: personally thinks that EKUs are a plague created by lawyers from hell, but accepts that they are a thing, and so we must document what is expected from the various pieces)

Initially, we suspect that lack of DigitalSignature EKU on IDevID is causing problems with Java keytool.

**Comment by pritikin** [comment]
from 802.1AR:

7.2.13 extensions
The optional extensions field defined in RFC 5280 shall not be used for critical extensions in any IDevID credential with the exception of the keyUsage extension. The non-critical extensions included are specified in 7.2.5 (authorityKeyIdentifier) and 7.2.9 (subjectAltName).
The key usage field defined in RFC 5280 is intended to restrict the associated key material to only the specified usages. The intention of an IDevID is to provide a long lived credential useful for identifying the device in any future protocol uses. Restrictions applied during issuance may limit the future usefulness of the DevID. If a critical keyUsage extension is included in the IDevID, it shall include digitalSignature as defined in RFC 5280. The keyUsage extension may include keyEncipherment.
The optional extensions field defined in RFC 5280 should not be used for critical extensions in any LDevID credential. As specified in RFC 5280 a network solution that uses the LDevID credentials and encounters a critical extension it does not understand will signal an error and fail validation of the LDevID credential.

**Comment by pritikin** [comment]
Similarly the language of RFC5280 is: 
4.2.1.3 Key Usage
"The usage restriction might be employed when a key that
   could be used for more than one operation is to be restricted." 
5280 goes on to only mandate these for "Conforming CAs MUST include this extension in certificates that
   contain public keys that are used to validate digital signatures on
   other public key certificates or CRLs."
