### ISSUE TITLE
does the "https://" need to always be on the MASA URL contents

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#123]
The IDevID that I produced look like:
            1.3.6.1.4.1.46930.2: 
                ..https://florean.sandelman.ca

The IDevID that Thomas (MASA-test-bt) produces:
            1.3.6.1.4.1.46930.2: 
                ..masa-test.siemens-bt.net:9443

Note that it is missing "https://"  ... This was done because there was some thought that coaps might be used between registrar and MASA.  We have never defined that though. Constrained BRSKI uses https between the registrar and MASA.
However, skipping 8 redundant bytes may be worth it.
So we should, I think, document that it is acceptable for the MASA_URL to be missing https://, that it is implied.

**Comment by pritikin** [comment]
thinking:
s2.3.2 "The URI provides the authority information. The BRSKI "/.well-known" tree ([RFC5785]) is described in Section 5." should be a simpler sentence.
and 
s5 clarify if we expect the entire https url or just the 'authority' string. does this sentence need to be normative?

**Comment by pritikin** [comment]
Add an example masa URI such as:
https://ietf.example.com/.well-known/est
