### ISSUE TITLE
MASA: accept option/header for voucher request

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-bootstrap#126]
This issue relates to: #124 , #125 

It looks like there are no details about the accept option/header for voucher requests received by MASA.  
If the MASA receives a voucher request without CoAP accept option or HTTP accept header (not set by pledge and also not set by registrar), it should determine the expected voucher response format from the prior-signed-voucher-request.  
Questions: Should MASA double check the accept option/header (if present) is conform with expected 
 voucher response format  according to prior-signed-voucher-request? How should MASA behave if not conform?

Accept header/option value for "/requestvoucher","/rv" requests. Supported values are:
"application/voucher-cms+json" (CoAP option: 65101) for JSON-in-PKCS#7/CMS,
"application/jose" (CoAP option: 65102) for JSON-in-JWS, or
"application/voucher-cose+cbor" (CoAP option: 65502) for CBOR-in-COSE_Sign.

**Comment by pritikin** [comment]
Proposal:
add a new section in between 5.5.4. and 5.5.5 wherein we mirror the language of the last half of 5.5.5 1st para similar to the following:

> The MASA is
   aware of which pledges accept which voucher formats and
   can use this information to verify consistency.

**Comment by pritikin** [comment]
Opted to add a bit of text into the existing section "MASA and Registrar Voucher Response" instead.
