### ISSUE TITLE
content-type for voucher-request uses voucher mime type.

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#128]
should we add an iana request for a new mime type?

**Comment by mcr** [comment]
Max Pritikin <notifications@github.com> wrote:
    > should we add an iana request for a new mime type?

Take it to the list.

**Comment by mcr** [comment]
Decided not to do this, can not do content-negotiation on POST, and it's not very DRY, since both JSON has type is there.
