### ISSUE TITLE
Offline operations #2

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#13]
Dear BRSKI authors

So i am building these networked military gear - weapons, drones, bombs, tanks etc. and i have to ship them to arbitrary battlefields in the world. The customers want to make sure that the weapons can not be abused before they take posession in the battlefield, and they do not  want to afford prestaging areas.

The logic of enrolling the gear when it is put into service in the battlefield sounds great, it should nicely protect the device during delivery and storage. Only problem:  the customer security folks also said they can not and want not have an online connection between battlefield and my MASA because they fear that connection could be tracked or because they are too cheap to afford it (satellites and all).

I was thinking of simply putting a voucher for the customer into the gear during manufacturing. Is this option supported in BRSKI and documented ? It seems not, eg: it would involve skipping the signaling steps to acquire the voucher....

**Comment by becarpenter** [comment]
Agree with Toerless. Similar concerns arise for safety-critical control systems where trust based on external connections is not acceptable. Pre-installing a voucher seems appropriate.

**Comment by mcr** [comment]
This scenario was already in scope.  The goal of appendix D isn't to remove functionality, but to permit us to reorganize text. It sounds like what you need is an application note that explains how to operate in an offline way.

**Comment by becarpenter** [comment]
Yes please, exactly that.

**Comment by pritikin** [comment]
"they do not want to afford prestaging areas" and "Pre-installing a voucher" seem like two statements that conflict with each other. But anyway...

I think the recent cleanup wrt to "offline" help clarify how the Registrar can "skipping the signaling steps to acquire the voucher" by obtaining it in advance and/or via whatever complex methods are desired. Note though that BRSKI is all about some form of online between the Pledge and the Registrar to avoid the "prestaging" problem. So if you want real true offline for all devices then you're basically talking about manual distribution of the voucher on a USB stick or something. In which case the raw voucher format and your own sneakernet solution is what you want (not BRSKI). This is why the voucher document lives on its own.

**Comment by becarpenter** [comment]
I've reviewed the latest text on offline operations and I agree. This seems to cover an 'air gap' scenario where the registrar goes online to obtain nonceless vouchers and then goes off line, possibly for ever. I think that would cover the tactical and safety-crtical networks that I've been concerned about.

**Comment by pritikin** [comment]
closing this issue. thanks for your attention to it.
