### ISSUE TITLE
insert new section explaining assertion types

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#133]
>    assertion: The method used to verify assertion.  See Section 5.5.5.

    > Section 5.5.5 doesn't define syntax of this field in enough details to
    > implement. Can it contain one of the allowed values (like C enum)?

**Comment by EskoDijk** [comment]
A reference to Section 5.3 of https://tools.ietf.org/html/rfc8366 could be sufficient to explain the assertion types. A new section is then maybe not needed.
