### ISSUE TITLE
serial-number mandatory in Voucher Request, or not?

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-bootstrap#137]
The YANG specifies "serial-number" as mandatory in Voucher Request, while section 5.2 text "The pledge populates the voucher-request fields as follows:" does not mention the serial-number and states that it MAY be omitted. (Due to "All other fields MAY be omitted in the pledge voucher-request."). That seems to contradict. I would expect serial-number to be mandatory.

**Comment by EskoDijk** [comment]
@mcr I saw there is some document updating being done, could this issue be addressed also in a next release?

I propose to include the "serial-number" field and a description in Section 5.2, since it is mandatory per the YANG definition of voucher-request.

**Comment by mcr** [comment]
We agree; the text became inconsistent as we considered whether or not we could trust the serial-number from the pledge.
