### ISSUE TITLE
Add IANA section for GRASP objective names: AN_Proxy and AN_join_registrar

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#147]
Add to IANA section:

The IANA is requested to register the value "AN_Proxy" (without quotes) to the GRASP Objectives Names Table in the GRASP Parameter Registry. The specification for this value is this document, Section 4.1.1

The IANA is requested to register the value "AN_Proxy" (without quotes) to the GRASP Objectives Names Table in the GRASP Parameter Registry. The specification for this value is this document, Section 4.3

**Comment by mcr** [comment]
Fixed in: commit f6a0e2fe2217d42940fedb6a0bd2491d0f8cc8ff
