### ISSUE TITLE
Common vouchers across BRSKI/NETCONF

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#17]
Assume the vendor service wants to deliver (ownership) vouchers to customer without having to bother whether NETCONF or BRSKI is used in the customer network.

If i understand it correctly, voucher draft asks for PKCS7 signature, BRSKI for JWS. One of the two solutions would need to support both signatures to allow single vouchers to be used across both.

I discuss here what we should add to BRSKI to support PKCS7 as an option:

1.  The media type for voucher responses should probably be application/voucher+pkcs7 or application/voucher+jws Depending on the format used. This seems to be the only way to distinguish the signature format of a response because otherwsie you can only guess what format the binary blob has.

2. The request media type can stay application/voucherrequest{,+cms} because it is IMHO fine to expect that registrar/MASA will always use JWS for requests. Nevertheless, the naming is highly illogical:

in the response media type, the name indicates the actual encoding, eg: voucher+cms/pkcs7/jws -
 because the data is cms=(pkcs7,jws) encoded.

In the reply, the request from pledge to MASA does indeed use JWS signature, but the mime type is application/voucherrequest. Vice versa, the voucher request to the MASA itself does not seem to have a signature but it is called application/voucherrequest+cm. Aka: the consistent mime types would be application/voucherrequest+jws for voucher request from pledge and application/voucherrequest for request from registrar to MASA.

**Comment by pritikin** [comment]
I too was finding the "+cms" stuff broken. It isn't even registered in the iana structured syntax suffic registry (https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml). I think we were just making trouble for ourselves. The current text I just committed backs this to a clear "voucher" and "unsignedvoucher" and leaves open the idea of more mediatypes without defining them. This is consistent with the approach we are taking in the voucher document now.
