### ISSUE TITLE
EST Distribution of CA certificates need text update

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#21]
The second paragraph of this section is not clear.

The term "domainCAcert" needs to be updated to the final terminology from the voucher document ("pinned-domain-cert"). The limitations to be discussed is that a "pinned-domain-cert" can be sufficient for a single connection but is *not* sufficient for PKIX validation of end entities. In order to support RFC5280 certificate path validation the full CA certificate distribution needs to be obtained.

**Comment by pritikin** [comment]
Figure 2 should also indicate: "verify provisional registrar certificate" in the figure.

**Comment by mcr** [comment]
resolved as per 18.
