### ISSUE TITLE
Question: multiple ACP addresses....

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#24]
Just a question to the Certificate expert, not really a BRSKI issue:

a) Can we have more than one rfc822 mail address (aka: ACP address) in a certificate ?
b) Can we use BRSKI to enroll more than one certificate - driven by the registrar
    (or if not by registrar, then by whom).

**Comment by pritikin** [comment]
re (b): I do not believe so for the following reason: BRSKI is only used when the device is unconfigured. 
EST can be used to enroll any number of times. GRASP is not defined for EST so discovering the EST registrar only works if the EST registration authority and the BRSKI registrar are always the same.

**Comment by pritikin** [comment]
A couple of additional points from design team meeting:
1) client needs to update certs to using BRSKI RA for this is logical.
2) BRSKI may be used if configured to do so. Preferably I think the current LDevID cert should be used for authorization of getting additional certs; but this is an operational choice i think. I don't like going to the BRSKI MASA multiple times as this leaks information about the local network. So i think focus on (1) above.

**Comment by mcr** [comment]
(a) yes, we can have more than one rfc822 address, and so more than one ACP name, but what would it *mean*?

**Comment by pritikin** [comment]
Planning on adding this text to into BRSKI-07, s3.8

        <t>
          Although EST allows clients to obtain multiple certificates by sending
          multiple CSR requests BRSKI mandates use of the CSR Attributes request
          and mandates that the Registrar validate the CSR against the expected
          attributes. This implies that client requests will "look the same" and
          therefore result in a single logical certificate being issued even if
          the client were to make multiple requests. Registrars MAY contain
          more complex logic but doing so is out-of-scope of this specification.
          BRSKI does not signal any enhancement or restriction to this
          capability. Pledges that require multiple certificates could establish
          direct EST connections to the Registrar.
        </t>
