### ISSUE TITLE
enrollment status telemetry

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#25]
This section indicates that the 'subjectkeyidentifier' be included in the telemetry indication. In the success case this would be a field extracted from the certificate issued. In the failure cases, either due to a failed EST /serverkeygen or due to a rejected request, the client can't actually form this field. The best we could do is normatively indicate that the RFC5280 "4.2.1.2.  Subject Key Identifier" method (1) is used if the client knows the keypair that was attempted.

This leaves a lot to be desired. In the success case it works but in the fail cases, the ones most likely to be examined, it is less than totally reliable. The one case it works well for though is when the client generates the keypair and fails to enroll, or when the certificate is issued - can be parsed - but can't be installed. All other failures would have to be logged by the server and associated with the enrollment session state: namely that the telemetry response was assocaited with a persistent TLS connection or something. Or associated with communications from this authenticated client. In which cases the inclusion of this field doesn't provide anything.

Suggested resolution then: drop this field entirely and indicate that it is up to the server to collate these telemetry messages based on client authentication. This reduces the requirements on the clients.

**Comment by mcr** [comment]
Max Pritikin <notifications@github.com> wrote:
    > This section indicates that the 'subjectkeyidentifier' be included in
    > the telemetry indication. In the success case this would be a field
    > extracted from the certificate issued. In the failure cases, either due
    > to a failed EST /serverkeygen or due to a rejected request, the client
    > can't actually form this field. The best we could do is normatively
    > indicate that the RFC5280 "4.2.1.2. Subject Key Identifier" method (1)
    > is used if the client knows the keypair that was attempted.

Hi, there is some context missing for me.
Is there any relationship to the concern that I raised in the email:

https://www.ietf.org/mail-archive/web/anima/current/msg02947.html

**Comment by pritikin** [comment]
I don’t think these are related. The issue I created (#25) should just be about the telemetry information (and to capture that we need to fix this).

Your concerns in the other thread are more broad: you’re questioning allowing claiming the device w/o enforcing either,

(1) Pledge signed the request and set assertion to ‘proximity’
(2) some out-of-scope sales channel integration
	Examples:
		Intel’s Marshal Point approach
		Direct claim during sales
		
ref:
   Pledge proximity assertion:  The MASA server MAY verify that the
      Registrar signed voucher includes the 'prior-signed-voucher' field
      populated with a Pledge signed voucher that includes a pinned-
      domain-cert that is consistent with the Registrar certificate
      chain.  The MASA server is aware of which Pledge's support signing
      of their voucher requests and can use this information to confirm
      proximity of the Pledge with the Registrar.

- max

**Comment by mcr** [comment]
we will remove the subjectKeyIdentifier field, but add a new "reason-context" field for the pledge to put whatever it likes in.

**Comment by mcr** [comment]
in commit: 1b0e094
