### ISSUE TITLE
ref RFC7159 or RFC7951? 

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#27]
Need to go through BRSKI and Voucher doc and verify the correct references.

**Comment by mcr** [comment]
RFC7159: The JavaScript Object Notation (JSON) Data Interchange Format
RFC7951: JSON Encoding of Data Modeled with YANG

Oh my. Both are actually relevant.  Not just a typo.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mcr** [comment]
I have been through the document, I don't think we actually ever need to reference 7159, because 7951 suits all references.   Maybe we should reference 7159 the first time we say JSON, but that time is actually a 7951 reference.
