### ISSUE TITLE
Add "voucher request" to terminology section

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#28]
Would also like to see an explanation why voucher request is defined here and voucher not.

Eg: The voucher itself is defined in RFX-XXX whereas the voucher request is defined in this document because the voucher is shared with other protocols (such as Netconf Call Home -
 RFC XXX) where there is no online voucher request.

**Comment by pritikin** [comment]
A comment was added to the introduction to clarify. How a voucher may be used is more appropriate for the voucher document itself. The intro to BRSKI indicates what a voucher request is and why it was added: 

<t>The syntactic details of vouchers are described in detail in <xref
      target="I-D.ietf-anima-voucher" />. This document details automated
      protocol mechanisms to obtain vouchers, including the definition
      of a necessary 'voucher request' message that is a minor extension
      to the voucher format (see <xref target="voucher-request" />).</t>
