### ISSUE TITLE
yang extensions

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#4]
BRSKI uses the current version of the YANG "revision" without indicating such in s2.1. We probably need to indicate the exact revision or use the netconf "out of band negotiation" (or something). 

This is an issue as we look toward extension of the yang. For example(!) "encapsulated vouchers" as presented from the pledge to the registrar that is then included in the voucher to the masa. Might want simpler examples. 

Currently we have no normative language around how relying parties  of vouchers handle unexpected extensions.

**Comment by pritikin** [comment]
This is necessary for the registrar to include a 'proximity assertion' which is not defined in the current yang model.

**Comment by pritikin** [comment]
One option: 
Define a "ietf-voucher-brksi"
make ietf-voucher vs ietf-voucher-brski optional
voucher doc uses "grouping" [this so brski can do 'uses'] ** change to voucher**
then when defining a voucher so that brski can "augment" to add the single field.
   This might be useful for BRSKI extensions we are currently discussion
   Another example use might be network endpoint assessment or other extension.

another option:
      anydata opaque {
        mandatory false;
        description
          "This field is for generic extensibility. The proper semantics must be defined elsewhere"
      } 
   MCR & Max: it feels weird to define this extensible 'anydata' in voucher but then 
   immediately use it up in BRSKI. This might still work as the Pledge could put in "anydata" then the registrar use would be 'prior-voucher' and the MASA would know how to dig down and find this. Problem:  an opaque field like this could be used to exfiltrate data and thus introduces a security concern. 
   FYI - an example of where this might be useful: to put network endpoint assessment information into this field. 
   
or:

anydata prior-voucher { # or "brski-use"
  mandatory false;
  description
          "If it is necessary to change or present a prior voucher then the original signed 
          voucher is included in this field.";
}

**Comment by pritikin** [comment]
Seems the best way forward is:
1) use the grouping etc to allow clear extensions in the future
also
2) use the well defined "prior-voucher" so we don't immediately have to talk about extensions

**Comment by pritikin** [comment]
This is what our discussion resolves to:

leaf prior-voucher { # or embedded-voucher-that-has-been-re-signed-or-modified
type binary; 
mandatory false;
description
"If it is necessary to change a voucher or include an supplemental voucher then the original signed
voucher is included in this field. This is useful if the Pledge signed a proximity voucher and the Registrar
also signs a Proximity voucher.";
}

**Comment by mcr** [comment]
lets add:
A prior-voucher object may itself have an embedded prior-voucher field.
No limit to embedding depth is standardized.

**Comment by pritikin** [comment]
I think all this was addressed
