### ISSUE TITLE
section 5.0 is an overview, it should have no details

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#52]
I think that the bullet'ed points in section 5.0 should only cover the general flow, with all specifics in subsequent sections.

**Comment by pritikin** [comment]
The bullets are a summary of changes from straight EST RFC7030 to support automation.
They could all be moved to a distinct "summary of updates to EST [RFC7030] for automation" subsection if you want. I don't have a strong preference.
