### ISSUE TITLE
replace dns-sd names

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#57]
<pre>
    > a) Use suggested service name of "_brski-proxy" in all caes where
    > "_bootstrapks" 
    > is used. (see comment for section 4.1.1 for why that name is better).
</pre>

also register brski-proxy and brski-registrar to service list.

**Comment by mcr** [comment]
Names in appendix B names updated per comment above.
Max to edit IANA considerations.

**Comment by pritikin** [comment]
https://github.com/anima-wg/anima-bootstrap/commit/f3aed687205c3e1975dc056f47a80b631c9277ae

I believe this to be closed now.
