### ISSUE TITLE
document valuation of audit log under different voucher-request scenarios

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#59]
A pledge's voucher-request may be signed or unsigned, and may contain a nonce or not.
This has impact upon the value attached to the contents of the audit log.
Document the different values.

**Comment by mcr** [comment]
@pritikin , I've pushed to a branch some text that I had in mind for the security consideration.
I'm trying to justify different amounts of faith in the audit log entries.  We may need to discuss this part more.

**Comment by pritikin** [comment]
We reviewed and merged and committed
