### ISSUE TITLE
clarify "serial-number" field for pledge signed uses

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#6]
we have indicated that the registrar would populate this with "what it expects/hopes" the masa will sign into the voucher (e.g. the pledge's serial number). but if the pledge is using a voucher to assert proximity then its actually indicating what it hopes the "pinned-domain-cert" would be. So maybe it makes more sense to *that field* to be what the pledge signs. 
so the request from the pledge looks like:

{
"nonce"
"created-on"
"assertion": "proximity"
"pinned-domain-cert" : <registrar cert>
"idev-id-issuer" : actual pledge's aki
"serial-number" : actual pledge serial number
}

this resolves the problem we were talking about re idev-id-issuer because it now is always used as the idev-id-issuer.

(it is expected that the pledge staples it's cert(s) to the pkcs#7/jws as per the full voucher spec)

**Comment by mcr** [comment]
This is addressed by proximity.

**Comment by pritikin** [comment]
Resolve in this fashion:
The pledge puts the 'pinned-domain-cert' as seen in the provisional TLS.
The registrar puts the 'idev-id-issuer', and 'serial-number' as seen in the provisional TLS.
Text of the doc needs an update fix this.

**Comment by pritikin** [comment]
closed as of merge of the proximity-domain-mumble branch
