### ISSUE TITLE
circuit proxy vs join proxy differences

### ISSUE THREAD

**Issue by pritikin** [anima-wg/anima-bootstrap#62]

**Comment by pritikin** [comment]
fixed with diff https://github.com/anima-wg/anima-bootstrap/commit/dac1f90609c979a347e0f966d428269ab0f30be3

MCR, in doing so I had to resolved cases of "Circuit Proxy" vs "Join Proxy" down to just "proxy". But in retrospect I'm unsure if this was correct. I think so. "Join Proxy" is defined in terminology but "Circuit Proxy" is used in a number of location. I stopped making changes regarding this and ask that you take a look.

**Comment by pritikin** [comment]
Related to the proxy question is this sentence which appears to be incomplete:
(and I left it unresolved)

"If GRASP is used by proxies for discovery of registrars (ACP or not), the proxy can also learn the proxy mechanism (circuit proxy vs. IPIP encapsulation or other)" 

"If GRASP is used by proxies for discovery of registrars (ACP or not), the proxy can also learn the proxy mechanism (circuit proxy vs. IPIP encapsulation or other)"

**Comment by mcr** [comment]
I'm less and less enthused with making Pledge and Registrar lower case.
Maybe we should keep them upper case in BRSKI.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by kwatsen** [comment]
sure can, but really the question is what the plan is for all the terms in the document.   

also note that even though brwski may capitalize stuff has zero effect on downstream documents referring to its terms.

**Comment by mcr** [comment]
I would prefer that Join Proxy remain a proper noun (upper-case).
We made Registrar and Pledge proper nouns as a result of Bill Atwood's review.
I think that they are things more than they are in voucher, and we should
backout your changes for lower-case.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by pritikin** [comment]
oh boy. 

So here was the guidance @kwatsen gave the IETF editors on the case discussion for voucher document: 
```
On Fri, Apr 06, 2018 at 05:27:59PM +0000, Kent Watsen wrote:
All these diffs look good to me.  

My only remaining comment is that I think the motivation that led to capitalizing "pledge" originally was to match the capitalization of "join registrar" (aka "registrar"). The intent to having consistency is a good one, and thus I think we should lowercase all terms.  Of the 10 terms defined in the draft, I think that Join Registrar/Registrar was the only one that was previously capitalized, so once made lowercase, then I think all the terms would be consistently lowercase.  [BTW, when I say "lowercase", I mean "case-insensitive"; if, e.g., at the beginning of a sentence, then I'd expect it to be capitalized]
```

This results in the auth48 final voucher document (https://www.rfc-editor.org/authors/rfc8366.txt) using lowercase versions of "pledge" and "registrar". I disagree but didn't feel it was mattered enough to interject with the auth48 process (I was out when the email exchange/change occurred). With the "intent to having consistency" the above diff brings these same changes to the BRSKI document. 

This is mostly independent of any issues regarding the type of proxies. There are "circuit proxy" and "ownership proxy" and just "proxy" used in the text. When downcasing for the above I got confused by this and switched this issue header. 

Here is what I will do next: 

a) back-out all changes to "ownership" "circuit" proxy etc so that that language is the original. I will maintain the new lowercase standard while doing this. 

b) work to understand and resolve any confusion regarding those proxy terms. at a minimum this means defining them better.

c) then i think we can answer the update/lowercase question independently.

**Comment by pritikin** [comment]
Completed (a). Didn't really backout as made a pass for consistency. See https://github.com/anima-wg/anima-bootstrap/commit/b47f6e5d82cdadcc78ffca928fc2269e56f813fa

Summary: 
* Added definitions for "join proxy" "circuit proxy" and "ipip proxy". addd to the definition of 'join proxy' that this document often will just say "proxy" (for readability) 
* Consistent use of just "proxy" where it didn't matter
* Double checked that each case it 'matters' to the text the appropriate long form is used. 
* a few minor editorial touch-ups. but please check me.

**Comment by pritikin** [comment]
My position on upcase/lowercase. I maintain my position that its clearer to use upcase for newly defined nouns but we moved away from that in the voucher doc and this doc reads ok without needing upcase. I vote the current text (lowercase) is ok with the couple of specific exceptions (like in diagrams).

**Comment by mcr** [comment]
ack

    > Here is what I will do next:

    > a) back-out all changes to "ownership" "circuit" proxy etc so that that language is the original. I will maintain the new lowercase standard while doing this.

    > b) work to understand and resolve any confusion regarding those proxy terms. at a minimum this means defining them better.

    > c) then i think we can answer the update/lowercase question independently.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mcr** [comment]
Max Pritikin <notifications@github.com> wrote:
    > My position on upcase/lowercase. I maintain my position that its
    > clearer to use upcase for newly defined nouns but we moved away from
    > that in the voucher doc and this doc reads ok without needing upcase. I
    > vote the current text (lowercase) is ok with the couple of specific
    > exceptions (like in diagrams).

I am okay with this, as long as the WG agrees.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mcr** [comment]
closing issue, opening new issue
