### ISSUE TITLE
Pledge Authorization section missing

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#66]
rev -16 section 5.2 has an unresolved EDNOTE pointing to a section for "Pledge Authorization". That section was last D.1.3.2.  in -07 and was then removed when D.* was integrated back and the rest of D was removed in -08. 

I can not find offhand any stubs of D.1.3.2 integrated elsewhere into the text, so i would suggest to reintroduce an appropriate subset of that section (aka: anything you think is uncontentuous).

**Comment by mcr** [comment]
Closed by introduction of new 5.3 section with text rescued from D.1.3.2.
