### ISSUE TITLE
nominate expert review

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#69]
C) Expert reviewer

Any suggested expert reviewer for the new voucher registry 
Short of an answer, If not, i'll recommend IANA to ask authors of RFC8366.

**Comment by mcr** [comment]
Need to designate experts. Expert to be designated:  Max and Michael.
To be added to Shepherd write up.

**Comment by EskoDijk** [comment]
@mcr This issue should be closed also, I think
