### ISSUE TITLE
Meaning of 'domain-cert-revocation-checks' in voucher-request undefined

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-bootstrap#75]
The Pledge can optionally include a 'domain-cert-revocation-checks' field in the voucher-request. It is not specified what the meaning of this field is, if included, in the voucher request. RFC 8366 only defines it for the voucher.
(Also no examples of inclusion of this field in the request are given.)

**Comment by mcr** [comment]
It appears that YANG's refine can not omit this field, so I am marking it as illegal in the description.
