### ISSUE TITLE
security review issue 4: abuse of long duration infinite vouchers by a previous owner

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#77]
4) Abuse of long duration timeless vouchers by a previous owner. This is
discussed in the security section.

**Comment by pritikin** [comment]
Nothing else to say. Its a reality to allow for either "ship and forget" style or network partitions etc.

**Comment by mcr** [comment]
section 6.2, pledge security reductions.
point 1, change how nonceless voucher support is explained in the context of the reduction.

section 9, security considerations expands upon MASA unavailable.

Is it possible that we  did not clearly answer: "what happens when a previous owner attempts to use a previous voucher to do an attack".
A voucher is only applicable when a device is in a bootstrap state.

Add section 1.3.x. Bootstrapping vs Booting.

**Comment by pritikin** [comment]
https://github.com/anima-wg/anima-bootstrap/commit/f16c442caf9b47288ba3040508114922c953ca52

(think i fixed this with the other)
