### ISSUE TITLE
security review issue 6: ship and forget not supported

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#79]
6) No "ship and forget" operation. BRSKI supposes continuous involment of
the manufacturer during the deployment process. This means that a whole
class of inexpensive devices are out of scope. This is a tradeoff between
usability and some security properties, and the tradeoff should be
explained.

**Comment by pritikin** [comment]
Sure it is. If you publish your voucher signing key you're in "ship and forget" mode. Of course you've also created devices pOwnable over the network.

Perhaps just admit that BRSKI isn't a good match for ship & forget

**Comment by pritikin** [comment]
shipping a device w/ a nonceless voucher without an identified registrar would be an extreme model?

better would be ship & forget with a voucher to a registrar cert that is then distributed (widely? with the device?)

**Comment by mcr** [comment]
Reply with email, out of scope.
(Can ship with nonceless, non-expiring voucher, that ships with a unique private key for the registrar)
