### ISSUE TITLE
security review issue 2: compromise of vendor's public key

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#80]
2) Compromise of the vendor's public key. This would allow attackers to get
"ugly ducklings" imprinted in the domain.

**Comment by pritikin** [comment]
There is very little to be said about the MASA voucher signing key. Perhaps a paragraph in the security considerations indicating that the MASA is recommended to use different keys for various groups of devices. there is a cost here -- the MASA/vendor now has a large(r) number of keys to manage and think about. 

This is implied by the use of certs for the voucher signing methods.

**Comment by mcr** [comment]
MASA rotating key.  "This is implied by the use of certs for the voucher signing methods."

**Comment by mcr** [comment]
Put this in a Security Considerations section: Long-term Management of MASA Key.

**Comment by mcr** [comment]
Russ asks:

> I think the security considerations ought to describe the consequences
> of compromise of the various private keys in the ecosystem.  Some only
> impact one device, but others have much greater impact.

**Comment by mcr** [comment]
We added section Manufacturer Maintainance of trust anchors . . . . . . .  69
