### ISSUE TITLE
security review issue 7: what if MASA always issues vouchers

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#82]
7) The closest to ship and forget is a MASA service configured to always
issue vouchers, regardless of the device ID and the registrar domain. I would
expect that to be popular with some manufacturers. It is mentioned in
section 6.4, which recommend that manufacturers should not do that. What
are the consequences if they still do?

**Comment by pritikin** [comment]
Ideally they at least enforce proximity (as noted in section 6.4). If they don't then the risk is that the log grows out of control and becomes so unwieldy that it is no longer maintained. As such the registrar will either accept the lowered security or stop accepting the devices.

At the final extreme a vendor can simply public their private key and walk away (allowing for open source MASA's to take up issuing vouchers for their devices). This is a reasonable extreme exit strategy for vendors (lame, but reasonable). 

ultimately the market will choose not to buy from those vendors.
