### ISSUE TITLE
security review issue 8: device refuses to be imprinted

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#83]
8) Attacks by the device. What happens if a device refuses to be imprinted?
I suppose someone will have to "resurrect the duckling". How costly is that?

**Comment by pritikin** [comment]
*IF* a device is still trusted after it refuses to be imprinted (thats a big IF) I guess one could attempt to wipe it to a clean state and try again. At some point, relatively quickly, it simply becomes cheaper to throw the device away and use a different one. 

Section 6.2 details the recommendation that:
"It is RECOMMENDED that "trust on first use" or skipping voucher
   validation only be available if hardware assisted Network Endpoint
   Assessment [RFC5209] is supported.  This recommendation ensures that
   domain network monitoring can detect innappropriate use of offline or
   emergency deployment procedures."
It could be clearer that this recommendation applies to any registrar willing to accept a device that refused vouchers until reset to clean state (as that implies it was previously imprinted). 
The logs should be checked!!

We could look for a public cost estimate on touching a device vs a zero touch brski flow. I think a few hundred dollars is a current estimate. So thats where you start trying to resurrect the duckling?

**Comment by mcr** [comment]
email reply only. Not the customers' problem, not a protocol problem. Ship it back.
