### ISSUE TITLE
security review issue 11: what if MASA refuses to provide a voucher

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#88]
11) Attacks by the MASA. What happens if the MASA refuses to provide a voucher,
or provides a wrong voucher? Can the MASA be used to restrain commerce
with specific countries? Is that a feature or a bug?

**Comment by pritikin** [comment]
If the MASA refuses to issue a voucher then use of the BRSKI protocol flow to bootstrap the device does not work. There are a number of methods a vendor can use to "restrain commerce" (e.g. make their own product less valuable) particularly when the device is paired with a cloud service.

The only protocol method would be to examine the IP address of the registrar and perform geolocation from there. If certain IP ranges were excluded by the vendor it would be relatively trivial to work around using either ip location masking or obtaining nonceless vouchers from acceptable locations.

**Comment by mcr** [comment]
... "although the MASA can be used to restrain the voucher, it can not be used to restrain the device"

**Comment by mcr** [comment]
"Privacy Considerations" section, discussed possible subsection "Used, Stolen or Grey Market equipment"... but MASA does not need to do such close tracker.
Does the protocol provide new opportunities for the vendor to insert themselves into the life-cycle of the device, but only in this protocol.
What about in the Trust Model section?  Where is the right place to explain the tradeoffs of using this protocol, vs not.
Decide to put this into 8.0 section, to explain how to this protocol facilities *complete* transfer of the device to the owners' network, dis-engaging the vendor from the day-to-day operation of the device.

**Comment by mcr** [comment]
@pritikin I would like your review, and if you like it, merge it.
