### ISSUE TITLE
gen art issue #6: nonce inside voucher?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#94]
Section 2.4:

>  P---Voucher Request (include nonce)------>|                    |

Is this nonce the one inside the voucher or something different?

**Comment by pritikin** [comment]
yes, the one in the voucher. 
there was an attempt on this image, e.g.
--optional:nonce--->
to provide a visual representation of the possible nonceless flows. Its clear to me but I've noted the comments where it confuses folks. Not sure how to address that other than two distinct diagrams with an explainer that "depending on the registrar's decision concerning nonces there may be two different flows".

I wish we could have suggested a cloud based protocol that never included 'nonceless' as an operation. But then we wouldn't have nonceless permanent vouchers. Which would have been a different problem.
