### ISSUE TITLE
gen art issue #8: example cert confusing

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#96]
Section 3.2:

> "proximity-registrar-cert": "base64encodedvalue=="

I do not understand the notation that you are using here, nor did my
grep for the above string find anything from the RFC directory other
than in RFC 8366. Is "base64encodedvalue==" a value that you are using
as an example, or some special format that signifies something else?

**Comment by pritikin** [comment]
My recollection is that this ensures that the yang stuff verifies correctly. The "==" is padding as per https://tools.ietf.org/html/rfc4648#section-6. Once we start using that as the example in the yang all examples end up with it.
