### ISSUE TITLE
gen art issue #9: proxy examination of TLS

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#97]
Section 4:

> A proxy MAY assume TLS framing for auditing purposes, but MUST NOT
> assume any TLS version.

Is this specification sufficient to understand what this means
from a actual behaviour point of view? Must pass all bytes unchanged?

**Comment by pritikin** [comment]
The value of assuming TLS framing is what? The ability to passively watch the handshake? As the TLS version changes the value of this might be reduced. Perhaps we don't need this normative statement at all? It doesn't change the functionality.

**Comment by mcr** [comment]
Removed implementation guidance on auditing, but leave statement about ignoring TLS version.
